# Практика 02. Базовые конструкции языка Python. Коллекции данных: строки, списки, кортежи, множества, словари. Решение прикладных задач

## Часть 01. Проверка условий

### Проверка условий

Начнем с известных всем операторов. Проверим,

* правда ли, что 8 меньше 9;
* правда ли, что 9 больше 10.

In [1]:
8 < 9 # правда

True

In [2]:
9 > 10 # неправда

False

Результат такой проверки имеет логический тип (*boolean*).

In [3]:
res = 8 < 9
res

True

Как мы уже обсуждали, переменные такого типа могут принимать два значения `True` или `False`. Обратите внимание, что `True` и `False` не заключены в кавычки – добавив кавычки, мы получим строки "True" и "False" (тип *string*).

In [4]:
'True' == True

False

При проверке равенства двух частей (переменных, списков и так далее) используется двойной знак равенства.

In [5]:
6 == 6

True

Одинарный знак «равно» используется для присваивания значений. Так ничего не сравним, но сохраним в переменную `a` число 6:

In [6]:
a = 6
a

6

А так уже проверим условия:

In [7]:
print(a == 6)
print(a == 9)

True
False


Отрицание равенства в Python обозначается с помощью оператора `!=` (вообще `!` в программировании используется для отрицания).

In [8]:
6 != 7

True

Стоит отметить, что Python достаточно лояльно относится к разделению между типам данных. Например, если мы сравним целое число и то же число, но с плавающей точкой (с дробной частью равной 0), Python сообщит, что эти числа совпадают.

In [9]:
6 == 6.0 # верно

True

### Сложные условия

Пусть у нас есть три целочисленные переменные `a`, `b` и `c`, и мы планируем составлять сложные, составные уcловия, касающиеся этих переменных.

In [10]:
a = 3
b = 7
c = 1

Помогут операторы `and` и `or`. Оператор `and` соответствует одновременному выполнению условий, оператор `or` соответствует ситуации, когда хотя бы одно из условий выполняется. Оператор `or` в Python – обычное «или», не исключающее: либо верно первое условие, либо второе, либо оба.

(15 < 17) and (17 > 10)<br>
True   and  True -> True

In [11]:
(a < b) and (b > c) # оба верны

True

(15 < 17) and (10 > 17)<br>
True  and False -> False

In [12]:
(a < b) and (c > b) # второе неверно -> все неверно

False

Вместо `and` можно использовать оператор `&`, он нам ещё пригодится при работе с датафреймами `pandas`:

In [13]:
(a < b) & (c > b)

False

(15 < 17) or (15 > 10)<br>
True or True - > True

In [14]:
(a < b) or (a > c) # первое верное -> хотя бы одно верно

True

Вместо `or` можно использовать оператор `|`:

In [15]:
(a < b) | (a > c)

True

Кроме `and` и `or` в Python есть еще полезные операторы: оператор принадлежности `in` и оператор отрицания `not`.

Пусть у нас есть списки отличных, хороших, удовлетворительных и плохих оценок.

In [16]:
excel = [8, 9, 10]
good = [6, 7]
sat = [4, 5]
bad = [1, 2, 3]

Проверим, лежит ли оценка 8 в плохих:

In [17]:
8 in bad

False

Применим отрицание:

In [18]:
8 not in bad # верно!

True

## Часть 02. Условные конструкции

<b>Условные операторы</b> в языках программирования (в том числе и в Python) необходимы в ситуациях, когда перед программой поставлена проблема выбора действия в зависимости от состояния переменных: если условие выполняется, то должен выполняться один набор действий, если нет – другой набор действий.<br>
Конструкцию <b>if-elif-else</b> еще называют <b>оператором ветвления</b>.

Синтаксис инструкции изображают в следующем виде:

In [19]:
if <условие 1>:
    <выражение 1>
elif <условие 2>:
    <выражение 2>

…

elif <условие n>:
    <выражение n>
else:
    <выражение n + 1>

SyntaxError: invalid character '…' (U+2026) (1139886720.py, line 6)

Структура следующая:<br>

- Всегда присутствует инструкция <b>if</b>;
- Ноль, одно или несколько выражений <b>elif</b>;
- Конечный оператор <b>else</b> не обязателен, но может использоваться, если все вышестоящие не сработали.

Рассмотрим синтаксис условного оператора на примере.<br>
Пусть от пользователя требуется ввести два целых числа: температуру на улице вчера и сегодня.<br>
А программа ответит — сегодня теплее, холоднее или же температура не изменилась.

In [20]:
yesterday_temp = int(input())

today_temp = int(input())

 3
 5


In [21]:
if today_temp > yesterday_temp:
    print('Сегодня теплее, чем вчера!')

elif today_temp < yesterday_temp:
    print('Сегодня холоднее, чем вчера!')

else:
    print('Сегодня такая же температура, как вчера!')

Сегодня теплее, чем вчера!


Оператор `if` является началом условной конструкции.<br>
Далее идёт условие, которое возвращает логическое значение `True` (истина) или `False` (ложь).<br>
Завершается условие символом «двоеточие».<br>
Затем — обязательный отступ в четыре пробела, он показывает, что строки объединяются в один блок.<br>
Отступ аналогичен использованию фигурных скобок или ключевых слов begin и end в других языках программирования.

Тело условной конструкции может содержать одно или несколько выражений (строк).<br>
По завершении тела может идти следующее условие, которое начинается с оператора `elif` (сокращение от else if — «иначе если»). Оно проверяется `только в случае`, если предыдущее условие `не было истинным`.

Синтаксис в `elif` аналогичен `if`.<br>
Операторов `elif` для одного блока условного оператора может быть несколько, а может не быть совсем.<br>
Последним идёт оператор `else`, который не содержит условия, а выполняется, только если ни одно из предыдущих условий в `if` и `elif` не выполнилось.<br>
Оператор `else` не является обязательным.

В качестве условия может выступать результат операции сравнения:

- `>` (больше);
- `>=` (больше или равно);
- `<` (меньше);
- `<=` (меньше или равно);
- `==` (равно);
- `!=` (не равно).

Для записи <b>сложных условий<b> можно применять логические операции:<br>

`and` — логическое «И» для двух условий. Возвращает True, если оба условия истинны, иначе возвращает False;<br>
`or` — логическое «ИЛИ» для двух условий. Возвращает False, если оба условия ложны, иначе возвращает True;<br>
`not` — логическое «НЕ» для одного условия. Возвращает False для истинного условия, и наоборот.

Изменим условие задачи.<br>
Пусть от пользователя требуется ввести два целых числа: температуру на улице вчера и сегодня.<br>
А программа ответит — сегодня теплее, если температура сегодня выше температуры вчера.

In [22]:
if today_temp > yesterday_temp:
    print('Сегодня теплее, чем вчера!')

Сегодня теплее, чем вчера!


Пусть от пользователя требуется ввести два целых числа: температуру на улице вчера и сегодня.<br>
А программа ответит — сегодня теплее, если температура сегодня выше температуры вчера,<br>
сегодня холоднее, если температура сегодня ниже температуры вчера.

In [23]:
yesterday_temp = int(input())

today_temp = int(input())

 11
 33


In [24]:
if today_temp > yesterday_temp:
    print('Сегодня теплее, чем вчера!')

elif today_temp < yesterday_temp:
    print('Сегодня холоднее, чем вчера!')

Сегодня теплее, чем вчера!


Пусть от пользователя требуется ввести два целых числа: температуру на улице вчера и сегодня.<br>
А программа ответит — сегодня теплее, если температура сегодня выше температуры вчера,<br>
иначе - сегодня холоднее.

In [25]:
if today_temp > yesterday_temp:
    print('Сегодня теплее, чем вчера!')

else:
    print('Сегодня холоднее, чем вчера!')

Сегодня теплее, чем вчера!


# Задание

1. Напишите программу, которая будет проверять, какое число сохранено в переменной <b>result</b> (значение вводится с клавиатуры).<br>
И если это число <b>меньше 25</b>, на экран будет выводиться сообщение `Слишком мало`, <b>иначе</b> - `Слишком много`.<br>

2. Изменим условие задачи.<br>

Если это число <b>меньше 25</b>, на экран будет выводиться сообщение `Слишком мало`, <b>меньше 50</b> - сообщение `Мало`, <b>равно 50</b> - сообщение `Отлично!`, <b>больше 50 (!но меньше 75)</b> - сообщение `Много`, <b>больше 75</b> - `Слишком много`.<br>
Подумайте, как оптимально можно реализовать условие: больше 50 (!но меньше 75).<br>

3. Продумайте и запишите <b>собственное условие задачи<b> с учетом трех вариантов ее решения:
- без использования конструкций `elif`, `else`;
- без использования конструкции `elif`, но с конструкцией `else`;
- без использования конструкций `else`, но с конструкцией `elif`.<br>

Напишите программы решения всех трех вариантов предложенной задачи.

In [32]:
result = int(input("Введите число: "))

Введите число:  36


In [33]:
if result < 25:
    print("Слишком мало")
else:
    print("Слишком много")

Слишком много


In [34]:
if result < 25:
    print("Слишком мало")
elif result < 50:
    print("Мало")
elif result == 50:
    print("Отлично!")
elif result < 75:
    print("Много")
else:
    print("Слишком много")

Мало


## Без использования конструкций elif, else

In [35]:
if result < 25:
    print("Слишком мало")
if 25 <= result < 50:
    print("Мало")
if result == 50:
    print("Отлично!")
if 50 < result < 75:
    print("Много")
if result >= 75:
    print("Слишком много")

Мало


## Без использования конструкции elif, но с конструкцией else

In [36]:
if result < 25:
    print("Слишком мало")
else:
    if result < 50:
        print("Мало")
    else:
        if result == 50:
            print("Отлично!")
        else:
            if 50 < result < 75:
                print("Много")
            else:
                print("Слишком много")

Мало


## Без использования конструкций else, но с конструкцией elif

In [37]:
if result < 25:
    print("Слишком мало")
elif result < 50:
    print("Мало")
elif result == 50:
    print("Отлично!")
elif 50 < result < 75:
    print("Много")
elif result >= 75:
    print("Слишком много")

Мало


Обратите внимание, что если в задаче несколько условий, то решение можно реализовать несколькими способами: через инструкцию `elif` или через `вложенную условную конструкцию`.

*Например*,<br>
мы просим пользователя ввести число, и если число больше 10, на экране должно появиться сообщение "больше 10",<br>
если равно 10 – "равно 10", если меньше – "меньше 10".<br>
Условные конструкции можно вкладывать друг друга, главное не забывать при этом про отступы:

In [38]:
x = 7

In [39]:
if x < 10:
    print('меньше 10')

else:
    if x == 10:
        print('равно 10')

    else:
        print('больше 10')

меньше 10


Можно воспользоваться оператором `elif`, который по смыслу является сочетанием `else + if`: если предыдущее условие невыполнено, то нужно проверить следующее условие, и если оно тоже не выполнено, то уже перейти к ветке с `else`.

In [40]:
if x < 10:
    print('меньше 10')

elif x == 10:
    print('равно 10')

else:
    print('больше 10')

меньше 10


Ответвлений с `elif` может быть несколько: сколько условий, столько и выражений с `elif`.

А можно ли обойтись совсем без `elif`, просто записав несколько выражений с `if`?<br>
Все зависит от ситуации. Иногда решения использовать `elif` и `if` будут равнозначными, иногда – нет.

*Рассмотрим задачу*.<br>
В переменной `mark` хранится оценка по 10-балльной шкале. Нужно вывести текстовый комментарий ("Excellent", "Good", "Satisfactory" или "Bad") в соотвествии с оценкой. Решим эту задачу с помощью `elif`:

In [41]:
excel = [8, 9, 10]
good = [6, 7]
sat = [4, 5]
bad = [1, 2, 3]

In [42]:
mark = 6

In [43]:
if mark >= 8:
    print('Excellent')

elif mark >= 6:
    print('Good')

elif mark >= 4:
    print('Satisfactory')

else:
    print('Bad')

Good


Почему мы можем сделать так? Потому что на каждом шаге, при проверке нового условия, мы сужаем круг интересующих нас исходов: если оценка не больше или равна 8, то она точно меньше 8 и сравнивать ее нужно только со следующей «пограничной» оценкой 6, далее, если оценка оказалась меньше 6, остается сравнить ее только с 4 и все.

Можно решить эту задачу без `elif`, а с помощью сложных условий:

In [44]:
mark = 6

In [45]:
if mark >= 8:
    print('Excellent')

if (mark < 8) and (mark >= 6):
    print('Good')

if (mark < 6) and (mark >= 4):
    print('Satisfactory')

if (mark < 4):
    print('Bad')

Good


В логическом операторе можно использовать **двойное неравенство**. Например, неравенство

In [46]:
if x >= 0 and x < 100:
    ...

лучше записать так:

In [47]:
if 0 <= x < 100:
        ...

Если бы в конце вместо последнего `if` мы написали конструкцию с `else`, результат был бы другим:

In [48]:
mark = 9

In [49]:
if mark >= 8:
    print('Excellent')

if (mark < 8) and (mark >= 6):
    print('Good')

if (mark < 6) and (mark >= 4):
    print('Satisfactory')

else:
    print('Bad')

Excellent
Bad


Почему? Потому что в этом случае часть с `else` относится не ко всем частям с `if` выше, а только к последней, где проверяется принадлежность `mark` промежутку от 6 до 8.

Рассмотрим еще один пример. Пользователь должен ввести первую и последнюю буквы русского алфавита. Ввод производится в двух отдельных строках и в любом регистре.

In [50]:
print('Введите первую и последнюю буквы русского алфавита')

first_letter = input()
last_letter = input()

Введите первую и последнюю буквы русского алфавита


 а
 я


Затем программа проверяет введенные символы и выводит на экран сообщение `Верно!`, если пользователь правильно ввел обе буквы, в противном случае - сообщение `Неверно!`.

In [51]:
if (first_letter == 'а' or first_letter == 'А') and (
    last_letter == 'я' or last_letter == 'Я'):

    print('Верно!')

else:
    print('Неверно!')

Верно!


**Строки** также **можно сравнивать между собой** с помощью операций >, < и т.д.<br>
В отличие от чисел, строки сравниваются посимвольно в соответствии с кодами символов в таблице кодировки (в Python рекомендуется использовать кодировку `UTF-8`).

Компьютер изначально работает только с двоичными числами. Поэтому для работы с символами им назначаются коды — числа, а сами таблицы соответствия символов и кодов называются `таблицами кодировки`. Кодировок существует достаточно много, одной из самых популярных на данный момент является `UTF-8`. Например, сравним две односимвольные строки:

In [52]:
letter_1 = 't'
letter_2 = 'w'

print(letter_1 > letter_2)

False


Программа выведет False, поскольку символ t стоит в таблице кодировки раньше, чем w (как и по алфавиту, то есть лексикографически). Чтобы убедиться в этом, можно использовать встроенную функцию `ord()`, которая возвращает код символа из таблицы кодировки:

In [53]:
print(ord('t'), ord('w'))

116 119


In [54]:
print(ord('Щ'), ord('ъ'))

1065 1098


Поскольку 116 меньше 119, в предыдущем примере мы и получили False.<br>
Чтобы получить символ по его коду, необходимо вызвать встроенную функцию `chr()` с соответствующим кодом:

In [55]:
print(chr(116), chr(119))

t w


В таблице кодировки большие и маленькие буквы являются различными символами с разными кодами (из разных диапазонов). Поэтому для корректного сравнения строки должны быть в одном регистре.

Для проверки условия наличия подстроки в строке используется оператор `in`. Например, проверим, что во введённой строке встречается корень «добр» (для слов «добрый», «доброе» и подобных):

In [56]:
text = input()

 добрый день


In [57]:
if 'добр' in text:
    print("Встретилось 'доброе' слово")

else:
    print("Добрых слов не найдено")

Встретилось 'доброе' слово


Попробуем сравнить строки:

In [58]:
'11' > '100'

True

In [59]:
print(ord('1'), ord('0'))

49 48


In [60]:
'Москва' > 'Челябинск'

False

In [61]:
'Москва' > 'Миасс'

True

Разберём другой пример. Нам необходимо обеспечить ввод имени, причём такого, чтобы оно было больше 3 символов, но меньше 50.<br>
Для начала надо задать переменную и ввести имя через клавиатуру:

In [62]:
name = input('Введите имя: ')

Введите имя:  Вадим


Теперь пропишем условия. «len» определяет длину слова, не забываем, что отсчёт начинается с «0».

In [63]:
if len(name) < 3:
    print('Имя должно состоять хотя бы из трех символов')

elif len(name) > 50:
    print('Имя не должно быть более 50 символов')

else:
    print('Имя введено верно')

Имя введено верно


# Задание

1. Пользователь вводит с клавиатуры два числа через пробел.<br>
Напишите код, который возвращает максимальное из двух введенных значений.

<b>Пример: </b>

Ввод:

    Введите два числа: 5.7 8
    
Вывод:

    8
    
*Подсказка:* вспомните работу со списками и функцию *split* из предыдущих лекций.

2. Дан список `N` из целых чисел. Напишите код, который делает следующее: выводит каждый элемент списка на экран и для каждого элемента либо выводит комментарий "Это четное число", либо комментарии "Это нечетное число".

*Подсказка:* используйте цикл for, оператор для нахождения остатка от деления – это `%`.

3. У питона есть набор любимых чисел.

    favorites = [3, 7, 11, 23, 18, 48, 81]

Напишите программу, которая просит пользователя ввести целое число, и если оно нравится питону, на экран будет выводиться сообщение: `"Мое любимое число!"`, если нет ‒ `"Эх, ну почему?"`.

In [1]:
numbers = input("Введите два числа через пробел: ")

number1, number2 = map(int, numbers.split())

max_number = max(number1, number2)

print(f"Максимальное число: {max_number}")

Введите два числа через пробел:  22 11


Максимальное число: 22


In [1]:
N = [11, 22, 33, 45, 56, 68, 77, 86, 97, 1070]

for number in N:
    if number % 2 == 0:
        print(f"{number} - Это четное число")
    else:
        print(f"{number} - Это нечетное число")

11 - Это нечетное число
22 - Это четное число
33 - Это нечетное число
45 - Это нечетное число
56 - Это четное число
68 - Это четное число
77 - Это нечетное число
86 - Это четное число
97 - Это нечетное число
1070 - Это четное число


In [2]:
favorites = [3, 7, 11, 23, 18, 48, 81]

user_number = int(input("Введите целое число: "))

if user_number in favorites:
    print("Мое любимое число!")
else:
    print("Эх, ну почему?")

Введите целое число:  11


Мое любимое число!


## Часть 03. Циклы в Python

- цикл с проверкой условия (**while**-loop)
- цикл с перебором значений (**for**-loop)

## Часть 04. Цикл for

Раз есть списки, хочется научиться «пробегаться» по их элементам. Например, выводить на экран не весь список `age` сразу, а постепенно, каждый элемент с новой строчки. Для этого есть циклы. Рассмотрим цикл *for*.

In [3]:
age = [23, 25, 32, 48, 19]  # возраст
age

[23, 25, 32, 48, 19]

In [4]:
for i in age:
    print(i)

23
25
32
48
19


Как устроен цикл выше? Кодом выше мы доносим до Python мысль:

* пробегайся по всем элементам списка `age` (`for i in age`);
* выводи каждый элемент на экран (`print(i)`).

Вообще любой цикл *for* имеет такую структуру: сначала указывается, по каким значениям нужно итерировать «пробегаться», а затем, что нужно делать. Действия, которые нужно выполнить в цикле, указываются после двоеточия в *for* – эта часть называется *телом* цикла.  

Буквы в конструкции *for* могут быть любые, совсем необязательно брать букву `i`. Python сам поймет, что мы имеем в виду, запуская цикл.

В качестве еще одного примера давайте для каждого элемента списка выведем на экран сообщение вида:

    x^2 – квадрат числа x.

In [5]:
# вместо i напишем a
for a in age:
    print(a ** 2, '– квадрат числа', a)

529 – квадрат числа 23
625 – квадрат числа 25
1024 – квадрат числа 32
2304 – квадрат числа 48
361 – квадрат числа 19


Теперь, используя цикл и специальный метод `.append()`, создадим новый список на основе старого – дополним пустой список преобразованными элементами старого списка. Метод `.append()` работает просто: он приписывает элемент в конец списка. Например, так:

In [6]:
print(age)  # до

age.append(76)

print(age)  # после

[23, 25, 32, 48, 19]
[23, 25, 32, 48, 19, 76]


Теперь создадим на основе старого списка `age` список `age2` с квадратами значений возраста:

In [7]:
age2 = []  # пока пустой список

In [8]:
for a in age:
    age2.append(a ** 2)

age2  # сработало!

[529, 625, 1024, 2304, 361, 5776]

Конечно, циклы нужны не только для того, чтобы работать со списками. С помощью циклов можно решить любую задачу, которая требует повторения одинаковых действий.<br>
Например, решим задачу про питона, который греется на солнышке и каждый день увеличивает время пребывания на солнце. Воспользуемся циклом.

In [9]:
# создадим список с номерами дней

days = [2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
# начальное значение времени, которое питон проводит на солнце

time = 1

print(1, time)

1 1


In [11]:
# теперь будем изменять значение time в цикле
# и выводить на экран номер дня и время

for d in days:

    time = time + 2
    print(d, time)

2 3
3 5
4 7
5 9
6 11
7 13
8 15
9 17
10 19


**Цикл с перебором значений**<br>
Выполняется для всех элементов коллекции или последовательности<br>

- диапазон целых чисел range
- элементы списка или множества
- отдельные буквы строки
- специальные функции, порождающие последовательности

Цикл **for**, также называемый **циклом с параметром**, в языке Python богат возможностями. В цикле **for** указывается **переменная** и множество значений, по которому будет пробегать переменная. Множество значений может быть задано *списком, кортежем, строкой или диапазоном*.

Простейший пример использования цикла, где в качестве множества значений используется кортеж:

In [12]:
i = 1

for color in 'red', 'orange', 'yellow', 'green', 'cyan', 'blue', 'violet':

    print('#', i, ' color of rainbow is ', color, sep = '')

    i += 1

#1 color of rainbow is red
#2 color of rainbow is orange
#3 color of rainbow is yellow
#4 color of rainbow is green
#5 color of rainbow is cyan
#6 color of rainbow is blue
#7 color of rainbow is violet


В этом примере переменная `color` последовательно принимает значения 'red', 'orange' и т.д. В теле цикла выводится сообщение, которое содержит название цвета, то есть значение переменной `color`, а также номер итерации цикла - число, которое сначала равно 1, а затем увеличивается на один (инструкцией i += 1 с каждым проходом цикла).

Инструкция `i += 1` эквивалентна конструкции `i = i + 1` (это просто сокращенная запись). Такую сокращенную запись можно использовать для всех арифметических операций: `*=, -=, /=, %=`...

В списке значений могут быть выражения различных типов, например:

In [13]:
for i in 1, 2, 3, 'one', 'two', 'three':
    print(i)

1
2
3
one
two
three


При первых трех итерациях цикла переменная `i` будет принимать значение типа `int`, при последующих трех — типа `str`.

**Итерация** — это повтор какого-либо действия. То есть один шаг цикла. Например, цикл из пяти повторений — пять итераций.<br>

**Итератор** — это интерфейс, который позволяет получить следующий объект последовательности.<br>

**Итерируемые объекты** — это объекты, которые можно повторять.

**Схема работы цикла for:**<br>
https://sky.pro/media/wp-content/webp-express/webp-images/uploads/2022/04/infografika-e1649859094396.png.webp

**Синтаксис цикла for:**

In [14]:
for <переменная> in <последовательность>:
    <действие>
else:
    <действие>

SyntaxError: invalid syntax (3680973736.py, line 1)

В Python цикл начинается с ключевого слова `for`, за которым следует произвольное имя переменной, которое будет хранить значения следующего объекта последовательности. Элементы «последовательности» перебираются один за другим «переменной» цикла; если быть точным, переменная указывает на элементы. Для каждого элемента выполняется «действие».

Блок `else` является особенным. Он будет выполнен только в том случае, если цикл не был «остановлен» оператором `break`. Таким образом, он будет выполнен только после того, как все элементы последовательности будут пройдены.

In [15]:
for i in 1, 2, 3, 'one', 'two', 'three':
    print(i)
else:
    print('else')

1
2
3
one
two
three
else


#### Оператор прерывания в python — break

Если в программе цикл `for` должен быть прерван оператором `break`, цикл будет завершен, и поток программы будет продолжен без выполнения действий из `else`.

Обычно фразы `break` в pyton связаны с условными операторами.

In [16]:
dinner = ['отбивные', 'пельмени', 'яйца', 'орехи']

In [17]:
for food in dinner:

    if food == 'пельмени':
        print('Я не ем пельмени!')

        break

    print('Отлично, вкусные ' + food)

else:
    print('Хорошо, что не было пельменей!')

print('Ужин окончен')

Отлично, вкусные отбивные
Я не ем пельмени!
Ужин окончен


Удалим «пельмени» из списка еды и получим следующее:

In [18]:
dinner = ['отбивные', 'яйца', 'орехи']

In [19]:
for food in dinner:

    if food == 'пельмени':
        print('Я не ем пельмени!')

        break

    print('Отлично, вкусные ' + food)

else:
    print('Хорошо, что не было пельменей!')

print('Ужин окончен')

Отлично, вкусные отбивные
Отлично, вкусные яйца
Отлично, вкусные орехи
Хорошо, что не было пельменей!
Ужин окончен


Еще один пример: необходимо прервать цикл, например, когда ожидали символ, а получили число, используем инструкцию `break`.

In [20]:
for chr in 'The t3st string':

    if chr.isdigit():
        break

    print(chr)

T
h
e
 
t


Дальше вывод не пойдет, так как слово t3st написано через тройку.<br>
Перейти на следующий шаг цикла можно с помощью инструкции `continue`.

#### Оператор пропуска python — continue

Предположим, «пельмени» нам нужно просто пропустить и продолжить прием пищи. Тогда нужно использовать оператор `continue` для перехода к следующему элементу.

В следующем маленьком скрипте `python` используем `continue`, чтобы продолжить, итерацию по списку, когда сталкиваемся с пельменями.

In [21]:
dinner = ['отбивные', 'пельмени', 'яйца', 'орехи']

In [22]:
for food in dinner:

    if food == 'пельмени':
        print('Я не ем пельмени!')

        continue

    print('Отлично, вкусные ' + food)

else:
    print('Ненавижу пельмени!')

print('Ужин окончен')

Отлично, вкусные отбивные
Я не ем пельмени!
Отлично, вкусные яйца
Отлично, вкусные орехи
Ненавижу пельмени!
Ужин окончен


In [23]:
for chr in 'The t3st string':

    if chr.isdigit():
        continue

    print(chr)

T
h
e
 
t
s
t
 
s
t
r
i
n
g


In [24]:
for i in range(10):

    if i % 3 == 0:
        continue

    print(i)

1
2
4
5
7
8


#### Итерация по спискам с функцией range()

Как правило, циклы `for` используются либо для повторения какой-либо последовательности действий заданное число раз, либо для изменения значения переменной в цикле от некоторого начального значения до некоторого конечного.

Для повторения цикла некоторое заданное число раз `n` можно использовать цикл `for` вместе с функцией `range`:

In [25]:
for i in range(4):  # равносильно инструкции for i in 0, 1, 2, 3:

    # здесь можно выполнять циклические действия
    print(i)
    print(i ** 2)

# цикл закончился, поскольку закончился блок с отступом

print('Конец цикла')

0
0
1
1
2
4
3
9
Конец цикла


В качестве `n` может использоваться числовая константа, переменная или произвольное арифметическое выражение (например, 2 ** 10). Если значение `n` равно нулю или отрицательное, то тело цикла не выполнится ни разу.

In [26]:
for i in range(-5):  # равносильно инструкции for i in 0, 1, 2, 3:

    # здесь можно выполнять циклические действия
    print(i)
    print(i ** 2)

# цикл закончился, поскольку закончился блок с отступом

print('Конец цикла')

Конец цикла


Функция `range` может также принимать не один, а два параметра. Вызов `range(a, b)` означает, что индексная переменная будеть принимать значения `от a до b - 1`, то есть первый параметр функции `range`, вызываемой с двумя параметрами, задает начальное значение индексной переменной, а второй параметр — первое значение, которое индексная переменная принимать не будет. Если же `a≥b`, то цикл не будет выполнен ни разу. Например, для того, чтобы просуммировать значения чисел `от 1 до n` можно воспользоваться следующей программой:

In [27]:
sum = 0
n = 5

for i in range(1, n + 1):
    sum += i

print(sum)

15


В этом примере переменная `i` принимает значения `1, 2, ..., n`, и значение переменной `sum` последовательно увеличивается на указанные значения.

Наконец, чтобы организовать цикл, в котором индексная переменная будет уменьшаться, необходимо использовать функцию `range` с тремя параметрами. Первый параметр задает начальное значение индексной переменной, второй параметр — значение, до которого будет изменяться индексная переменная (не включая его!), а третий параметр — величину изменения индексной переменной. Например, сделать цикл по всем нечетным числам `от 1 до 99` можно при помощи функции `range(1, 100, 2)`, а сделать цикл по всем числам `от 100 до 1` можно при помощи `range(100, 0, -1)`.

Если нужно получить доступ к `индексам списка`, не очевидно как использовать цикл `for` для этой задачи.<br>
Мы можем получить доступ ко всем элементам, но индекс элемента остается недоступным.<br>
Есть способ получить доступ как к индексу элемента, так и к самому элементу.<br>
Для этого используйте функцию `range()` в сочетании с функцией длины `len()`:

In [28]:
fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21]

In [29]:
for i in fibonacci:

    print(i)

0
1
1
2
3
5
8
13
21


In [30]:
for i in range(len(fibonacci)):

    print(i,fibonacci[i])

0 0
1 1
2 1
3 2
4 3
5 5
6 8
7 13
8 21


*Примечание*. Если применить len() к list или tuple, получим соответствующее количество элементов этой последовательности.

#### Enumerate в python 3

`Enumerate` — встроенная функция Python. Она позволяет автоматически считать итерации цикла.

In [31]:
for counter, value in enumerate(some_list):
    print(counter, value)

NameError: name 'some_list' is not defined

In [ ]:
my_list = ['яблоко', 'банан', 'вишня', 'персик']

In [ ]:
for c, value in enumerate(my_list, 1):
    print(c, value)

Функция `enumerate` принимает необязательный аргумент (значение начала отсчета, по умолчанию 0), который делает ее еще более полезной.

# Задание
Напишите программу, которая получает от пользователя **строку целых чисел**, и выводит:

- Количество положительных чисел.
- Произведение всех отрицательных чисел.
- Минимальное и максимальное числа **без** использования функций **min()** и **max()**.

**Пример:**

*Входные данные:*
        
3 -5 2 4 12 7 3 4 6 9 25 -50 12 35 2 11
    
*Выходные данные:*
        
Количество положительных чисел: 14<br>
Произведение отрицательных чисел: 250<br>
Минимальное число: -50<br>
Максимальное число: 35

*Подсказка: в цикле используйте условный оператор*

In [33]:
numbers = input("Введите строку целых чисел через пробел: ")
numbers_list = list(map(int, numbers.split()))

positive_count = 0
negative_product = 1  
minimum = maximum = numbers_list[0]

for num in numbers_list:
    if num > 0:
        positive_count += 1
    if num < 0:
        negative_product *= num
    if num < minimum:
        minimum = num
    if num > maximum:
        maximum = num

print(f"Количество положительных чисел: {positive_count}")
print(f"Произведение отрицательных чисел: {negative_product}")
print(f"Минимальное число: {minimum}")
print(f"Максимальное число: {maximum}")

Введите строку целых чисел через пробел:  3 -5 2 4 12 7 3 4 6 9 25 -50 12 35 2 11


Количество положительных чисел: 14
Произведение отрицательных чисел: 250
Минимальное число: -50
Максимальное число: 35


### Как работать с циклом for в Python

Цикл `for` работает со встроенными типами данных. Например, строки, списки, множества, кортежи, словари и даже файлы.

**Циклы в строках**<br>
Символы в строке можно вывести один за другим с помощью цикла for.

In [34]:
# выведем буквы в слове Питон

for i in 'Питон':
    print(i)

П
и
т
о
н


Иногда в алгоритмах нужно применять альтернативные инструкции для объектов, которые не проходят проверку. Выведем на печать каждый символ строки, меняя нижний регистр на верхний:

In [35]:
for chr in "THis is THe TEst sTRinG":

    if chr.islower():
        print(chr.upper())

    else:
        print(chr)

T
H
I
S
 
I
S
 
T
H
E
 
T
E
S
T
 
S
T
R
I
N
G


**Циклы в списках**<br>

In [36]:
# поочередно выведем элементы списка

number_list = [1, 2, 3]

In [37]:
# не забывая про двоеточие и отступ

for number in number_list:
    print(number)

1
2
3


Такого же результата можно добиться с помощью функции `range`, которая генерирует последовательность чисел.

In [38]:
# список

elems = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
# итерация по списку

for item in elems:
    print(item)

0
1
2
3
4
5
6
7
8
9


In [40]:
# итерация по числам с нуля до 10 не включительно

for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


**Циклы с шагом**<br>

Например, если нужно отобразить каждое второе число из списка, можно сделать проверку на деление с остатком. Алгоритм:

- получить размерность множества;<br>
↓
- отнять от этого числа единицу;<br>
↓
- итерировать по множеству чисел с нуля до полученного числа включительно;<br>
↓
- получить элементы списка, используя индексацию.

In [41]:
# кортеж

elems = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

# получаем размерность

length = len(elems)

In [42]:
# нам не нужно отнимать единицу, так как
# крайнее число в range не входит в последовательность
# первое число тоже не указываем
# по умолчанию — оно равно нулю

for i in range(length):

    # если остатка нет — выводим число
    if i % 2 == 0:
        print(elems[i])

0
2
4
6
8


А можно выполнить с помощью шага в функции `range`:

In [43]:
# каждое второе число от 0 до 10

for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


**Циклы в словарях**<br>

Итерацию по словарю проводят тремя способами. Первый и второй способ дают очередной ключ и очередное значение словаря на каждом шаге. Третий — и ключ, и значение за один шаг.

In [44]:
mydict = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five"}

In [45]:
# итерация по ключам

for key in mydict:

    print(f"{key} :: {mydict[key]}")

1 :: one
2 :: two
3 :: three
4 :: four
5 :: five


In [46]:
# по ключам с явным указанием

for key in mydict.keys():

    print(f"{key} :: {mydict[key]}")

1 :: one
2 :: two
3 :: three
4 :: four
5 :: five


In [47]:
# итерация по значениям

for value in mydict.values():

    print(value)

one
two
three
four
five


In [48]:
# итерация по ключам и значениям
# применяется распаковка кортежа вида (ключ, значение)

for key, value in mydict.items():

    print(key, value)

1 one
2 two
3 three
4 four
5 five


In [49]:
# создадим словарь, значениями которого будут списки из двух элементов

d = {'apple' : [3, 'kg'], 'tomato' : [6, 'pcs'], 'carrot' : [2, 'kg']}

In [50]:
# затем создадим две переменные-контейнера и применим метод .items()

for k, v in d.items():
    print(k, v)

apple [3, 'kg']
tomato [6, 'pcs']
carrot [2, 'kg']


Помимо этого мы можем вывести только ключи или только значения с помощью методов .keys() и .values() соответственно.

In [51]:
# возьмем только одну переменную и применим метод .values()

for v in d.values():

  # значение представляет собой список, выведем его первый элемент с индексом [0]
  print(v[0])

3
6
2


Помимо этого мы можем вложить один цикл for в другой (nested for loops). Предположим, что у нас есть следующая база данных клиентов.

In [52]:
# предположим, что у нас есть следующая база данных клиентов

clients = {1: {'name': 'Анна', 'age': 24, 'sex': 'male', 'revenue': 12000},
           2: {'name': 'Илья', 'age': 18, 'sex': 'female', 'revenue': 8000}}

База данных представляет собой словарь. Ключами являются id клиентов. Значениями — еще один (вложенный) словарь с информацией о каждом клиенте.

Ключами второго (вложенного) словаря выступают названия полей (ФИО, возраст, пол и выручка с клиента), а значениями — соответствующая информация. Выведем все эти данные.

In [53]:
# в первом цикле for поместим id и информацию о клиентах в переменные id и info

for id, info in clients.items():

  # выведем id клиента
  print('client ID: ' + str(id))

  # во втором цикле возьмем информацию об этом клиенте (это тоже словарь)
  for k, v in info.items():

    # и выведем каждый ключ (название поля) и значение (саму информацию)
    print(k + ': ' + str(v))

  # добавим пустую строку после того, как выведем информацию об одном клиенте
  print()

client ID: 1
name: Анна
age: 24
sex: male
revenue: 12000

client ID: 2
name: Илья
age: 18
sex: female
revenue: 8000



*Примечание*

- Обратите особое внимание на отступы слева, они указывают на очередность выполнения операций. Например, пустая команда print() (и соответственно пустая строка) имеет один отступ, чтобы исполниться после каждого клиента, а не после каждого поля с информацией о клиенте.
- При использовании функции print() мы можем объединить несколько строк, а вот объединить строку и число нельзя. Так как id, значение возраста (age) и значение выручки (revenue) являются числами (тип int), их нужно сначала принудительно сделать строкой через функцию str().

**Функция range() для списков и цикла for**

Иногда нам нужно создать последовательность чисел и пройтись по ней в цикле. Конечно, можно создать список и заполнить его нужными элементами, но, во-первых, для этого надо написать много кода, во-вторых, это будет неэффективно с точки зрения памяти компьютера. Для этого есть специальная функция range().

Функция range() принимает от одного до трех параметров.

- Если передать только один параметр, то мы начнем последовательность с нуля и закончим на элементе, предшествующем нашему параметру. В примере выше мы передали параметр «пять» (range(5)) и получили последовательность 0, 1, 2, 3, 4.
- Если указать два параметра, то мы начнем последовательность с первого параметра и законим на элементе, предшествующем второму параметру. В частности, если написать range(1, 6), то получится 1, 2, 3, 4, 5.
- Третий параметр устанавливает шаг. По умолчанию он равен единице, однако если, например, написать, range(0, 6, 2), то мы получим 0, 2, 4.

In [54]:
# создадим последовательность от 0 до 4

for i in range(5):
    print(i)

0
1
2
3
4


In [55]:
# от 1 до 5

for i in range(1, 6):
    print(i)

1
2
3
4
5


In [56]:
# и от 0 до 5 с шагом 2 (то есть будем выводить числа через одно)

for i in range(0, 6, 2):
    print(i)

0
2
4


In [57]:
# возьмем месяцы года

months = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']

# и продажи мороженого в тыс. рублей в каждый из месяцев

sales = [47, 75, 79, 94, 123, 209, 233, 214, 197, 130, 87, 55]

Что интересно, если совместить range() с функцией len(), то такую конструкцию можно использовать для того, чтобы в одном цикле вывести все элементы, например, двух списков по их индексу.

In [58]:
# задав последовательность через range(len())

for i in range(len(months)):

  # мы можем вывести каждый из элементов обоих списков в одном цикле
  print(months[i], sales[i])

Январь 47
Февраль 75
Март 79
Апрель 94
Май 123
Июнь 209
Июль 233
Август 214
Сентябрь 197
Октябрь 130
Ноябрь 87
Декабрь 55


**Функция enumerate() для списков и цикла for**

Мы можем использовать эту функцию, если у нас есть, например, список и, проходясь в цикле по этому списку, мы хотим также получить порядковый номер (индекс) элементов списка.

In [59]:
# пусть дан список со днями недели

days = ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье']

In [60]:
# выведем индекс (i) и сами элементы списка (day)

for i, day in enumerate(days):
    print(i, day)

0 Понедельник
1 Вторник
2 Среда
3 Четверг
4 Пятница
5 Суббота
6 Воскресенье


Все бы хорошо, но неделю логичнее начинать с первого дня, а не с нулевого. Для этого функции enumerate() можно передать начальное значение.

In [61]:
# так же выведем индекс и элементы списка, но начнем с 1

for i, day in enumerate(days, 1):
    print(i, day)

1 Понедельник
2 Вторник
3 Среда
4 Четверг
5 Пятница
6 Суббота
7 Воскресенье


**Обратный цикл**

Встроенная функция `reversed` и слайсинги (срезы) позволяют проводить итерацию по объекту в обратном порядке.

In [62]:
elems = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [63]:
# пример

for item in reversed(elems):
    print(item)

9
8
7
6
5
4
3
2
1
0


In [64]:
# пример использования слайсингов

for item in elems[::-1]:
    print(item)

9
8
7
6
5
4
3
2
1
0


**Генератор**

Инструкция `for` есть в различных выражениях-генераторах, например, генераторе списка или словаря.

In [65]:
import random

In [66]:
# так мы сделаем список из 20 случайно сгенерированных чисел

mylist = [random.randint(0, 11) for _ in range(20)]
mylist

[1, 0, 5, 3, 8, 3, 2, 4, 9, 3, 10, 3, 7, 5, 8, 5, 0, 5, 7, 9]

**Главное о цикле for**
- For перебирает элементы и выполняет код, который записан в теле цикла. В его основе лежат последовательности.
- Главное условие успешной работы цикла — объект должен быть итерируемым.
- Итерацию проводят по многим встроенным структурам данных: строки, словари, списки, множества, кортежи. Внутри инструкции создают ветвления в алгоритме с помощью проверок.
- Чтобы прервать цикл, используйте ключевое слово break. Чтобы пропустить элемент итерируемого множества — continue.

## Часть 05. Цикл `while`

С циклом `for` мы уже знакомы. Сейчас мы познакомимся с циклом `while`, логика которого отличается от `for`. Конструкции с циклом `while` устроены следующим образом: действия, которые указаны в теле цикла, должны выполняться до тех пор, пока верно условие, прописанное после `while` (отсюда и название). Если в цикле `for` мы указывали некоторый промежуток, по которому в ходе цикла мы будем «пробегаться», то в случае с циклом `while` мы просто фиксируем стартовую точку, а конечную точку никак не указываем: программа сама остановится, когда условие в цикле перестанет выполняться.

Давайте, используя цикл `while`, будем выводить на экран элементы списка `turnout` до тех пор, пока не столкнемся со странным значением явки (больше 100).<br>
`turnout` - процент явки на выборы по регионам

In [67]:
turnout = [68, 45, 98, 56, 70, 146, 56, 67]

In [68]:
i = 0 # начинаем с индекса i=0

In [69]:
while turnout[i] < 100: # пока элемент nums[i] >= 0

    print(turnout[i]) # выводим элемент на экран
    i = i + 1 # переходим к следующему элементу

68
45
98
56
70


На значении 70 мы остановились: за ним идет значение 146, для которого условие `turnout[i] < 100` не выполняется. Python не ожидал такого подвоха и перестал с нами разговаривать :)

Давайте теперь попробуем переписать код так, чтобы он работал точно так же, но только чтобы в нем использовался цикл `for`, а не `while`. Вообще почти любой код с `while` можно переписать через `for`, и иногда это полезно: код с циклом `while` обычно более медленный, плюс, склонен к зацикливанию.

In [70]:
for t in turnout:

    if t < 100:
        print(t)

    else:
        break # выходим из цикла

68
45
98
56
70


В коде выше мы использовали оператор `break`, который позволяет выйти из цикла, то есть закончить исполнение строк кода в теле цикла и перейти к коду дальше.  

In [71]:
for t in turnout:

    if t < 100:
        print(t)

68
45
98
56
70
56
67


Если бы мы хотели модифицировать код таким образом, чтобы он пропускал странное значение, ничего не делал, можно было бы добавить оператор `pass` вместо `break` (отвечает за отсутсвие действия):

In [72]:
for t in turnout:

    if t < 100:
        print(t)

    else:
        pass

68
45
98
56
70
56
67


А теперь напишем маленькую игру-угадайку. Программа будет загадывать целое число от 1 до 100, а пользователь его угадывать. Как программа будет загадывать число? Выбирать случайным образом из интервала [1, 100] (на самом деле псевдослучайным образом, так как абсолютной случайности не получится, генерирование чисел происходит по фиксированным алгоритмам).

In [73]:
from random import randrange # импортируем модуль для функии randrange

In [74]:
n = randrange(1, 101) # n и есть загаданное число

Осталось написать цикл. До тех пор, пока пользователь не угадает число, программа не будет останавливаться, но зато она будет давать подсказки: если введенное пользователем число больше загаданного, то будет выводиться сообщение "Вы ввели слишком большое число.", если меньше – "Вы ввели слишком маленькое число."

In [75]:
while True:
    guess = int(input('Ваша попытка:'))

    if guess == n:
        print('Вы выиграли!')
        break

    elif guess > n:
        print('Вы ввели слишком большое число.')

    else:
        print('Вы ввели слишком маленькое число.')

Ваша попытка: 21


Вы ввели слишком маленькое число.


Ваша попытка: 222


Вы ввели слишком большое число.


Ваша попытка: 100


Вы ввели слишком большое число.


Ваша попытка: 50


Вы ввели слишком большое число.


Ваша попытка: 40


Вы ввели слишком большое число.


Ваша попытка: 30


Вы ввели слишком большое число.


Ваша попытка: 22


Вы ввели слишком маленькое число.


Ваша попытка: 25


Вы ввели слишком маленькое число.


Ваша попытка: 26


Вы ввели слишком маленькое число.


Ваша попытка: 27


Вы ввели слишком маленькое число.


Ваша попытка: 28


Вы выиграли!


В коде выше в `while` мы не написали никакого условия явно, вместо этого мы написали `while True`. Это выражение означает «до тех пор, пока мы не вышли из цикла». В нашем случае это равносильно «до тех пор, пока не столкнулись с `break`», пока наш ответ не совпал с загаданным числом. Неформально можно считать, что конструкция `while True` – своеобразная альтернатива «бесконечному» циклу `for`.

### Рассмотрим теорию по циклу While

**Цикл с проверкой условия**<br>
Выполняется до тех пор, пока условие не станет ложным, или пока явно не сделать выход из цикла (break) или из функции (return).

Цикл **while** будет выполняться до тех пор, пока верно заданное в нем условие.

В целом все просто, но есть один нюанс.<br>
**Условие должно в какой-то момент перестать быть верным**, иначе цикл станет бесконечным. Для этого существует счетчик (counter).

In [76]:
# зададим начальное значение счетчика

i = 0

# пока счетчик меньше трех

while i < 3:

  # в каждом цикле будем выводить его текущее значение
  print('Текущее значение счетчика:  ' + str(i))

  # внутри цикла не забудем "нарастить" счетчик
  i = i + 1

  # и выведем новое значение
  print('Новое значение счетчика:    ' + str(i))

  # добавим пустую строку
  print()

Текущее значение счетчика:  0
Новое значение счетчика:    1

Текущее значение счетчика:  1
Новое значение счетчика:    2

Текущее значение счетчика:  2
Новое значение счетчика:    3



Рассмотрим еще раз, как мы получили такой результат.

- У нас есть начальное значение счетчика, равное нулю (i = 0) (хотя конечно значение счетчика может быть любым)
- При первой итерации, так как 0 < 3, исполняем код в цикле и увеличиваем счетчик на 1 (теперь i = 1)
- На второй итерации, 1 < 3, условие по-прежнему верно, снова исполняем код и увеличиваем счетчик на 1 (i = 2)
- На третьей итерации, 2 < 3, условие верно, исполняем код и увеличиваем счетчик на 1 (i = 3)
- Далее, алгоритм пытается выполнить четвертую итерацию цикла, однако так как 3 < 3 неверно, цикл прерывается

In [77]:
# тот же код можно упростить

i = 0

while i < 3:
    print(i)

    # в частности, оператор += сразу увеличивает и присваивает новое значение

    i += 1

0
1
2


In [78]:
x = 0
y = 5

In [79]:
while x < y:

    print(x, end=' ')
    x += 1  # Или x = x + 1

0 1 2 3 4 

In [80]:
x = 0
y = 5

In [81]:
while x < y:

    print(x, end=' ')
    x += 1  # Или x = x + 1

else:
    print('Happy End!')

0 1 2 3 4 Happy End!


In [82]:
x = 0
y = 5

In [83]:
while x < y:

    print(x, end=' ')
    x += 1

    if x > y-2: break
else:
    print('Happy End!')

0 1 2 3 

#### Break, continue в цикле while

Ходом исполнения цикла можно управлять.

**Оператор break**

Представьте, что вы пишете цикл, который затем примените к очень длинному словарю или списку (в нем, например, 10 тыс. элементов), но вы не уверены в своем коде. Если цикл применить сразу ко всему объекту и при этом окажется, что код делает не совсем то, что вы хотите, то придется ждать, пока компьютер выведет все 10 тыс. записей.<br>

Логично протестировать код на первой записи, а уже потом двигаться дальше. В этом нам поможет оператор break (прерывание цикла).

In [84]:
# вновь возьмем словарь clients

clients = {1: {'name': 'Анна', 'age': 24, 'sex': 'male', 'revenue': 12000},
           2: {'name': 'Илья', 'age': 18, 'sex': 'female', 'revenue': 8000}}

In [85]:
# в цикле пройдемся по ключам и значениям словаря

for id, info in clients.items():

  # и выведем их
  print(id, info)

  # однако уже после первого исполнения цикла, прервем его
  break

1 {'name': 'Анна', 'age': 24, 'sex': 'male', 'revenue': 12000}


Цикл можно также прерывать при наступлении определенного условия.

In [86]:
# начальное значение счетчика
x = 6

# будем исполнять цикл пока x не равен нулю

while x != 0:

  # выведем текущее значение счетчика
  print(x)

  # и уменьшим (!) его на 1
  x -= 1

  # если значение счетчика станет равным 3, прервем цикл
  # if x == 3:
    # break

6
5
4
3
2
1


Мы прервали цикл, когда значение счетчика стало равно трем.<br>

Также обратите внимание, что здесь цикл двигается в сторону уменьшения (с помощью -=). Мы начали с x = 6 и должны были вывести значения 6, 5, 4, 3, 2, 1, если бы условие не прервало выполнение цикла.

**Оператор continue**

Иногда цикл не нужно прерывать, но нужно как бы «перескочить» одну или несколько итераций этого цикла. В этом случае применяется оператор continue.<br>

Предположим, нам нужно создать последовательность целых чисел от 1 до 10 включительно и вывести только четные числа.

In [87]:
# выведем все четные числа в диапазоне от 1 до 10 включительно.

# с помощью функции range создадим последовательность от 1 до 10 с шагом 1
for i in range(1, 11):

  # если остаток от деления на два не равен нулю (то есть число нечетное)
  if i % 2 != 0:

    # идем к следующему числу последовательности
    continue

  # в противном случае выводим число
  else:
    print(i)

2
4
6
8
10


In [88]:
a = 15

In [89]:
while a:

    a = a - 1 # a -= 1

    if a % 2 != 0: continue
    print(a, end=' ')

14 12 10 8 6 4 2 0 

In [90]:
my_sum = 0

In [91]:
while True:

    val = int(input('Введите значение: '))

    if val == 0: break
    my_sum += val

    print('Текущая сумма: ', my_sum)

print('Конечная сумма: ', my_sum)

Введите значение:  12


Текущая сумма:  12


Введите значение:  32


Текущая сумма:  44


Введите значение:  23


Текущая сумма:  67


Введите значение:  11


Текущая сумма:  78


Введите значение:  2


Текущая сумма:  80


Введите значение:  1


Текущая сумма:  81


Введите значение:  3


Текущая сумма:  84


Введите значение:  0


Конечная сумма:  84


# Задание
Напишите программу, которая составляет **строку из полученных от пользователя слов**, пока длина строки не достигнет 50 символов. Слова, начинающиеся с гласных, в строку не включаются.

**Пример:**

*Входные данные:*
       
о<br>
бойся<br>
Бармаглота<br>
сын<br>
он<br>
так<br>
свиреп<br>
и<br>
лик<br>
а<br>
в глуще<br>
рымит
    
*Выходные данные:*
        
бойся Бармаглота сын так свиреп лик в глуще рымит

In [101]:
def is_vowel(word):
    vowels = 'аеёиоуыэюяАЕЁИОУЫЭЮЯ'
    return word[0].lower() in vowels

result = ''
length = 0

In [102]:
while length < 50:
    word = input("Введите слово: ")
    if not is_vowel(word):
        if length + len(word) + 1 <= 50:
            if length > 0:
                result += " "
            result += word
            length += len(word) + 1

Введите слово:  о
Введите слово:  бойся
Введите слово:  Бармаглота
Введите слово:  сын
Введите слово:  он
Введите слово:  так
Введите слово:  свиреп
Введите слово:  и
Введите слово:  лик
Введите слово:  а
Введите слово:  в глуще
Введите слово:  рымит


In [103]:
print(result)

бойся Бармаглота сын так свиреп лик в глуще рымит
